/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./layout/components/AppMain.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
    BusinessOrderCard: typeof import('./components/business/OrderCard.vue')['default']
    BusinessPerformanceMonitor: typeof import('./components/business/PerformanceMonitor.vue')['default']
    BusinessProductCard: typeof import('./components/business/ProductCard.vue')['default']
    BusinessStatPanel: typeof import('./components/business/StatPanel.vue')['default']
    BusinessUserAvatar: typeof import('./components/business/UserAvatar.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    EnhancedProductList: typeof import('./components/EnhancedProductList.vue')['default']
    HeaderBar: typeof import('./layout/components/HeaderBar.vue')['default']
    ItemIcon: typeof import('./layout/components/ItemIcon.vue')['default']
    Navbar: typeof import('./layout/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./layout/components/Sidebar.vue')['default']
    SidebarItem: typeof import('./layout/components/SidebarItem.vue')['default']
    StatsCard: typeof import('./components/StatsCard.vue')['default']
    UiActionMenu: typeof import('./components/ui/ActionMenu.vue')['default']
    UiDateRangePicker: typeof import('./components/ui/DateRangePicker.vue')['default']
    UiFormTable: typeof import('./components/ui/FormTable.vue')['default']
    UiLazyImage: typeof import('./components/ui/LazyImage.vue')['default']
    UiSearchFilter: typeof import('./components/ui/SearchFilter.vue')['default']
    UiStatusTag: typeof import('./components/ui/StatusTag.vue')['default']
    UiThemeManager: typeof import('./components/ui/ThemeManager.vue')['default']
    UiUploadManager: typeof import('./components/ui/UploadManager.vue')['default']
    VirtualTable: typeof import('./components/VirtualTable.vue')['default']
    VirtualTableTest: typeof import('./components/VirtualTable-Test.vue')['default']
  }
}

// For TSX support
declare global {
  const AppMain: typeof import('./layout/components/AppMain.vue')['default']
  const Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
  const BusinessOrderCard: typeof import('./components/business/OrderCard.vue')['default']
  const BusinessPerformanceMonitor: typeof import('./components/business/PerformanceMonitor.vue')['default']
  const BusinessProductCard: typeof import('./components/business/ProductCard.vue')['default']
  const BusinessStatPanel: typeof import('./components/business/StatPanel.vue')['default']
  const BusinessUserAvatar: typeof import('./components/business/UserAvatar.vue')['default']
  const ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
  const ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const EnhancedProductList: typeof import('./components/EnhancedProductList.vue')['default']
  const HeaderBar: typeof import('./layout/components/HeaderBar.vue')['default']
  const ItemIcon: typeof import('./layout/components/ItemIcon.vue')['default']
  const Navbar: typeof import('./layout/components/Navbar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Sidebar: typeof import('./layout/components/Sidebar.vue')['default']
  const SidebarItem: typeof import('./layout/components/SidebarItem.vue')['default']
  const StatsCard: typeof import('./components/StatsCard.vue')['default']
  const UiActionMenu: typeof import('./components/ui/ActionMenu.vue')['default']
  const UiDateRangePicker: typeof import('./components/ui/DateRangePicker.vue')['default']
  const UiFormTable: typeof import('./components/ui/FormTable.vue')['default']
  const UiLazyImage: typeof import('./components/ui/LazyImage.vue')['default']
  const UiSearchFilter: typeof import('./components/ui/SearchFilter.vue')['default']
  const UiStatusTag: typeof import('./components/ui/StatusTag.vue')['default']
  const UiThemeManager: typeof import('./components/ui/ThemeManager.vue')['default']
  const UiUploadManager: typeof import('./components/ui/UploadManager.vue')['default']
  const VirtualTable: typeof import('./components/VirtualTable.vue')['default']
  const VirtualTableTest: typeof import('./components/VirtualTable-Test.vue')['default']
}