-- 支付对账批次表
CREATE TABLE `reconciliation_batch` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `batch_no` varchar(50) NOT NULL COMMENT '对账批次号',
  `reconciliation_date` varchar(10) NOT NULL COMMENT '对账日期(YYYY-MM-DD)',
  `payment_type` tinyint(4) NOT NULL COMMENT '支付方式(1:微信支付 2:余额支付)',
  `system_transaction_count` int(11) DEFAULT 0 COMMENT '系统交易笔数',
  `system_total_amount` decimal(18,2) DEFAULT 0.00 COMMENT '系统交易总金额',
  `platform_transaction_count` int(11) DEFAULT 0 COMMENT '平台交易笔数',
  `platform_total_amount` decimal(18,2) DEFAULT 0.00 COMMENT '平台交易总金额',
  `success_count` int(11) DEFAULT 0 COMMENT '对账成功笔数',
  `fail_count` int(11) DEFAULT 0 COMMENT '对账失败笔数',
  `reconciliation_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '对账状态(0:未开始 1:处理中 2:已完成 3:失败)',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_no` (`batch_no`),
  KEY `idx_date_type` (`reconciliation_date`,`payment_type`),
  KEY `idx_status` (`reconciliation_status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='支付对账批次表';

-- 支付对账记录表
CREATE TABLE `reconciliation` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `batch_no` varchar(50) NOT NULL COMMENT '对账批次号',
  `reconciliation_date` varchar(10) NOT NULL COMMENT '对账日期(YYYY-MM-DD)',
  `payment_type` tinyint(4) NOT NULL COMMENT '支付方式(1:微信支付 2:余额支付)',
  `payment_no` varchar(50) DEFAULT NULL COMMENT '支付流水号',
  `transaction_id` varchar(100) DEFAULT NULL COMMENT '支付平台交易号',
  `order_no` varchar(50) DEFAULT NULL COMMENT '订单号',
  `order_amount` decimal(18,2) DEFAULT 0.00 COMMENT '订单金额',
  `actual_amount` decimal(18,2) DEFAULT 0.00 COMMENT '实际支付金额',
  `platform_amount` decimal(18,2) DEFAULT 0.00 COMMENT '平台金额',
  `reconciliation_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '对账状态(0:未对账 1:对账成功 2:金额不符 3:平台有本系统无 4:本系统有平台无)',
  `diff_amount` decimal(18,2) DEFAULT 0.00 COMMENT '差异金额',
  `error_reason` varchar(255) DEFAULT NULL COMMENT '错误原因',
  `solve_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '解决状态(0:未解决 1:已解决)',
  `solution` varchar(500) DEFAULT NULL COMMENT '解决方案',
  `solver` varchar(50) DEFAULT NULL COMMENT '解决人',
  `solve_time` datetime DEFAULT NULL COMMENT '解决时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_batch_no` (`batch_no`),
  KEY `idx_date_type` (`reconciliation_date`,`payment_type`),
  KEY `idx_payment_no` (`payment_no`),
  KEY `idx_transaction_id` (`transaction_id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_status` (`reconciliation_status`),
  KEY `idx_solve_status` (`solve_status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='支付对账记录表';