-- 用户表
CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `student_no` VARCHAR(20) NOT NULL COMMENT '学号',
  `nickname` VARCHAR(50) NOT NULL COMMENT '昵称',
  `phone` VARCHAR(20) DEFAULT NULL COMMENT '手机号码',
  `sex` TINYINT(1) DEFAULT NULL COMMENT '性别',
  `avatar` VARCHAR(255) DEFAULT NULL COMMENT '头像',
  `status` TINYINT(1) DEFAULT 0 COMMENT '状态: 0-正常, 1-禁用',
  `is_verified` TINYINT(1) DEFAULT 0 COMMENT '认证状态',
  `balance` DECIMAL(10,2) DEFAULT 0.00 COMMENT '账户余额',
  `score` INT DEFAULT 0 COMMENT '用户积分',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_student_no` (`student_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
