-- 用户认证表
CREATE TABLE IF NOT EXISTS `user_auth` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '认证ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `open_id` VARCHAR(100) NOT NULL COMMENT '微信OpenID',
  `union_id` VARCHAR(100) DEFAULT NULL COMMENT '微信UnionID',
  `session_key` VARCHAR(100) DEFAULT NULL COMMENT '会话密钥',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_open_id` (`open_id`),
  CONSTRAINT `fk_user_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户认证表';
