-- 商家表
CREATE TABLE IF NOT EXISTS `store` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '商家ID',
  `name` VARCHAR(100) NOT NULL COMMENT '商家名称',
  `logo` VARCHAR(255) DEFAULT NULL COMMENT '商家Logo',
  `phone` VARCHAR(20) NOT NULL COMMENT '商家电话',
  `address` VARCHAR(200) NOT NULL COMMENT '商家地址',
  `business_hours` VARCHAR(200) DEFAULT NULL COMMENT '营业时间',
  `description` TEXT DEFAULT NULL COMMENT '商家描述',
  `status` TINYINT(1) DEFAULT 0 COMMENT '商家状态',
  `rating` DECIMAL(3,2) DEFAULT 0.00 COMMENT '商家评分',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家表';
