-- 订单表
CREATE TABLE IF NOT EXISTS `order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `order_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '订单编号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `store_id` BIGINT NOT NULL COMMENT '商家ID',
  `total_amount` DECIMAL(10,2) NOT NULL COMMENT '总金额',
  `delivery_fee` DECIMAL(10,2) DEFAULT 0.00 COMMENT '配送费',
  `pay_amount` DECIMAL(10,2) NOT NULL COMMENT '实付金额',
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '订单状态',
  `pay_status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '支付状态',
  `delivery_status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '配送状态',
  `delivery_type` TINYINT(1) DEFAULT 1 COMMENT '配送方式',
  `contact_name` VARCHAR(50) NOT NULL COMMENT '联系人姓名',
  `contact_phone` VARCHAR(20) NOT NULL COMMENT '联系人电话',
  `delivery_address` VARCHAR(500) NOT NULL COMMENT '配送地址',
  `delivery_locker_code` VARCHAR(20) DEFAULT NULL COMMENT '外卖柜编号',
  `remarks` TEXT DEFAULT NULL COMMENT '订单备注',
  `paid_at` TIMESTAMP NULL DEFAULT NULL COMMENT '支付时间',
  `delivered_at` TIMESTAMP NULL DEFAULT NULL COMMENT '配送时间',
  `completed_at` TIMESTAMP NULL DEFAULT NULL COMMENT '完成时间',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_status` (`status`),
  KEY `idx_order_no` (`order_no`),
  CONSTRAINT `fk_order_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_order_store_id` FOREIGN KEY (`store_id`) REFERENCES `store` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
